name: my_urbanito
description: "A new Flutter project."

# La siguiente línea previene que el paquete sea publicado accidentalmente a pub.dev usando `flutter pub publish`.
# Esto es preferido para paquetes privados.
publish_to: "none" # Elimina esta línea si deseas publicar en pub.dev

# Versión y número de compilación para tu aplicación.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.8
  # Google Maps para Flutter
  google_maps_flutter: ^2.3.0
  # Para dibujar polilíneas (rutas)
  flutter_polyline_points: ^1.0.0
  # Para obtener la ubicación actual
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/gifmapa.gif

# Para asegurarte de que las fuentes personalizadas están correctamente configuradas
fonts:
  - family: Schyler
    fonts:
      - asset: fonts/Schyler-Regular.ttf
      - asset: fonts/Schyler-Italic.ttf
        style: italic
  - family: Trajan Pro
    fonts:
      - asset: fonts/TrajanPro.ttf
      - asset: fonts/TrajanPro_Bold.ttf
        weight: 700
# Asegúrate de que los assets y fuentes existen en las ubicaciones especificadas.
